---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: fedora


run:
  dir: code-src
  path: ../code-src/ci/scripts/change-request

inputs:
- name: code-src
- name: build-resource
