---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

run:
  dir: code-src
  path: ci/scripts/create-release

inputs:
- name: resource-version
- name: code-src
- name: build-resource


