github-uri: https://github.com/karthidec/DemoRepoJava.git
github-semver-uri: https://github.homedepot.com:Gatekeeper/application-manager-semver.git
github-credentials-uri: https://github.com/karthidec/DemoRepoJava-credentials.git
github-org-name: karthidec
github-repo-name: DemoRepoJava
concourse-url: https://concourse-pipeline-engineering.apps-np.homedepot.com
tracker-project-id: "2026577"
cf-org: Gatekeeper
cf-space: services
sonar-project-key: apper-keeper-aggregator
sonar-project-name: apper-keeper-aggregator
min-pr-approvers: 2
tracker-approvers: 2970112, 1445198
qualityhub-application-name: Gatekeeper-ApperKeeperAggregator
qualityhub-job-set: Tests
qualityhub-job-name: Unit Tests
cr-assigned-to: cgk0o7
cr-template: CD0001001
cr-snowfield-url: https://snowfield-homedepotuat.apps-np.homedepot.com
docker-image-repo: docker.artifactory.homedepot.com/java
docker-image-tag: 8
project-language: java
artifact-pattern: 'artifacts/app.jar'
