#!/bin/bash

echo "Version is: "
VERSION_NUMBER=$(cat ../$VERSION)
echo $VERSION_NUMBER


curl -u $GITHUB_USER:$GITHUB_TOKEN -X POST \
  https://github.homedepot.com/api/v3/repos/$OWNER_REPO/releases \
  -H 'content-type: application/json' \
  -d "{
  \"tag_name\": \"v${VERSION_NUMBER}\",
  \"target_commitish\": \"master\",
  \"name\": \"v${VERSION_NUMBER}\",
  \"body\": \"Automated release of ${VERSION_NUMBER}\",
  \"draft\": false,
  \"prerelease\": false
}"