#!/usr/bin/env ruby
require 'yaml'
require 'fileutils'

branch = ENV['BRANCH'].gsub(/^(chore|bug|feature)-(.*)$/i,"\\2")
branch = branch.squeeze('-').strip

manifest_content = File.open('./dev.manifest.yml', 'r').read
manifest_yaml = YAML.load(manifest_content)

manifest_yaml['applications'].each do |application|

  puts "Updating \"#{application['name']}\""
  application['name'] = application['name']+'-'+branch
  application['name'] = application['name'].squeeze('-')
  puts "\tNew Host: #{application['name']}"
  
end

deploy_manifest_content = YAML.dump(manifest_yaml)
deploy_manifest_location = '../deploy-info/dev.manifest.yml'

puts "Outputting deploy manifest to #{deploy_manifest_location}"
FileUtils.cp('./base.manifest.yml', '../deploy-info/base.manifest.yml')
File.write(deploy_manifest_location, deploy_manifest_content)
