#!/bin/bash
echo "Project Language--" $PROJECT_LANGUAGE

if [[ $PROJECT_LANGUAGE = "java" ]]
 then
    ./gradlew test

    BRANCH_NAME=$(git show-ref --heads | sed -e 's?.* refs/heads/??')

    java -Dsonar.projectKey=$PROJECT_KEY -Dsonar.projectName=$PROJECT_NAME -Dsonar.projectVersion=$BRANCH_NAME -Dproject.settings=sonar.properties -Dproject.home=. -Dsonar.java.binaries=build/classes/ -jar $SONAR_HOME/sonar-runner-dist-2.4.jar -e -X

    # -Dsonar.projectVersion=$BRANCH_NAME
 fi


 if [[ $PROJECT_LANGUAGE = "js" ]]
 then
  BRANCH_NAME=$(git show-ref --heads | sed -e 's?.* refs/heads/??')

    java -Dsonar.projectKey=$PROJECT_KEY -Dsonar.projectName=$PROJECT_NAME -Dsonar.projectVersion=$BRANCH_NAME -Dproject.settings=sonar.properties -Dproject.home=. -jar $SONAR_HOME/sonar-runner-dist-2.4.jar -e -X

 fi
