#!/usr/bin/env ruby
require 'yaml'

branch = ENV['BRANCH'].gsub(/^(chore|bug|feature)-(.*)$/i,"\\2")
branch = branch.squeeze('-').strip

manifest_content = File.open('code-src/dev.manifest.yml', 'r').read
manifest_yaml = YAML.load(manifest_content)

puts "Generating app urls"

app_urls=[]
manifest_yaml['applications'].each do |application|

  application['name'] = application['name']+'-'+branch
  application['name'] = application['name'].squeeze('-')

  app_urls.push('https://' + application['name'] + ".apps-np.homedepot.com")

end

comment = "Check out changes at " + app_urls.join(", ")

comment_file_location = './comments/comments.txt'

comment_file=File.open(comment_file_location, 'w')

comment_file.write(comment)

puts "Tracker comment: " + comment
