#!/bin/bash

# This is to get the branch name from a detached head investigating why in detached head state
HEAD=$(git show-ref --heads | sed -e 's?.* refs/heads/??')
ORG=$(echo $OWNER_REPO | awk '{split($0,a,"/"); print a[1]}')

Update_Build_Resource () {
    git config --global user.email "${GITHUB_USER}@homedepot.com"
    git config --global user.name "${GITHUB_USER}"
    git add Pull_Request_Number
    git commit -m "Update pull request number"
}

curl -u $GITHUB_USER:$GITHUB_TOKEN -X POST \
  https://github.homedepot.com/api/v3/repos/$OWNER_REPO/pulls \
  -H 'content-type: application/json' \
  -d "{
  \"title\": \"${HEAD}\",
  \"head\": \"${HEAD}\",
  \"base\": \"${BASE}\"
}" > openPullRequest.json

pull_request_number=$(cat openPullRequest.json | grep "\"number" | awk '{split($0,a,":"); print a[2]}' | awk '{split($0,a,","); print a[1]}' | awk '{ gsub (" ", "", $0); print}')

# Move into build-resource in order to upload file to update-build
cd ../build-resource

if [[ -z ${pull_request_number} ]]
then
    #If the pull request number is empty then this may be because a pull request already exists. Making the call below to validate if that's true.
    curl -u $GITHUB_USER:$GITHUB_TOKEN -X GET \
    https://github.homedepot.com/api/v3/repos/$OWNER_REPO/pulls?head=${ORG}:${HEAD} \
    -H 'content-type: application/json' > openPullRequest.json
    pull_request_number=$(cat openPullRequest.json | grep "\"number" | awk '{split($0,a,":"); print a[2]}' | awk '{split($0,a,","); print a[1]}' | awk '{ gsub (" ", "", $0); print}')
    #If the pull request number is empty then a previous pull request did not exist
    if [[ -z ${pull_request_number} ]]
    then
        echo "Pull request creation was unsuccessful."
        exit 11
    else
        #Need to update the build resource with the correct pull request number
        echo "Pull request was created previously. Updating build resource with pull request number: $pull_request_number"
        echo $pull_request_number > Pull_Request_Number
        Update_Build_Resource
    fi
else
    echo "Pull request number: $pull_request_number has been created"
    echo $pull_request_number > Pull_Request_Number

    Update_Build_Resource

fi
git clone ./ ../update-build
