#!/bin/bash

echo "Compressing src folder to upload to fortify server..."

# $SERVER_FOLDER (OPTIONAL Parameter) is used only for NodeJS projects where the server folder is outside src/

tar -cf app.tar $SRC_FOLDER $SERVER_FOLDER

echo "Uploading app.tar file to fortify server for scan..."

curl -k -X POST https://lnc3fd5.homedepot.com:9443/upload -H 'authorization: Bearer '$FORTIFY_TOKEN -H 'content-type: multipart/form-data;' -F 'file=@app.tar' > scanUpload.json

fileIndicant=$(cat scanUpload.json | grep "\"fileIndicant" | awk '{split($0,a,":"); print a[2]}' | awk '{ gsub ("}", " ", $0); print}' | awk '{ gsub ("\"", " ", $0); print}')

if [ ! -z "$fileIndicant" ]
then
    curl -X POST https://viper-static-scan-service.apps-np.homedepot.com/api/scan -H 'authorization: Bearer '$FORTIFY_TOKEN -H 'content-type: application/json' -d "{\"projVer\": \"$PROJECT_VERSION\" , \"language\": \"$PROJECT_LAN\" , \"payloadFile\": \"$fileIndicant\", \"emailList\": \"$EMAIL\"}" > scanUpload.json

    scanUpload_status=$(cat scanUpload.json | grep "\"status" | awk '{split($0,a,":"); print a[3]}' | awk '{ gsub ("}", " ", $0); print}' | awk '{ gsub ("\"", " ", $0); print}')
    echo $scanUpload_status

    if [ $scanUpload_status = "success" ]
        then
        echo "static scan success"
        exit 0
    else
        echo "static scan fail"
        exit 1
    fi

else
       scanUpload_status=$(cat scanUpload.json | grep "\"status" )
       echo $scanUpload_status
    exit 1
fi


