platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker.artifactory.homedepot.com/flow/java
    tag: "latest"
inputs:
  - name: code-src
outputs:
  - name: version
run:
  dir: code-src
  path: ci/scripts/flow-release-setup.sh
