---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 'latest'

run:
  path: code-src/ci/scripts/tracker-story-comment

inputs:
- name: code-src

outputs:
- name: comments